merge in some of webofunni's latest changes
 Changes to be committed:
	modified:   imdbdump

diff --git a/imdbdump/imdbdump b/imdbdump/imdbdump
--- a/imdbdump/imdbdump
+++ b/imdbdump/imdbdump
@@ -1,10 +1,10 @@
-#!/bin/bash - 
+#!/bin/bash -
 #===============================================================================
 #
 FILE=imdbdump
-VER=0.3b
+VER=0.4a
 #
-#         USAGE: ./imdbdump 
+#         USAGE: ./imdbdump
 #
 #   DESCRIPTION: Bash script to search and dump IMDb info.
 #
@@ -15,14 +15,14 @@ VER=0.3b
 #                While also working to add new features like the ratings bar and eventually a plug for
 #                miNfo 2. The old and semi broken miNfo can be found at https://github.com/dumbterminal/DT-miNfo
 #                imdbmoviefetcher written by Unni unnikrishnan.a@gmail.com
-#        AUTHOR: Mike Redd (MikereDD), mikeredd@mobileinfer n.us
+#        AUTHOR: Mike Redd (MikereDD), mikeredd@mobileinfern.us
 #  ORGANIZATION: Dumb Terminal Team
 #       CREATED: 07/21/2012 06:20:12 PDT
-#      REVISION: 10/13/2012 07:56:14 PD
+#      REVISION: 06/22/2014 16:26:43 PD
 #===============================================================================
 shopt -s -o nounset
 
-#Global variable declarations
+### Start Global variable declarations
 declare -rx GITREPO="https://github.com/MikereDD/imdbdump.git"
 declare -rx SCRIPT=${0##*/}
 declare -rx VERSION="${VER}"
@@ -54,129 +54,142 @@ declare -rx UNIQ=`which uniq`
 declare -rx HEAD=`which head`
 declare -rx SORT=`which sort`
 declare -rx CUT=`which cut`
+declare -rx TR=`which tr`
 declare SWITCH
-declare -r OPTSTRING=":hvt:"
+declare -r OPTSTRING=":hvpmst:"
 declare -i INEEDCOLOR
 declare TITLECOLOR="White"
 declare DATACOLOR="White"
 declare LINKCOLOR="White"
 declare FILECOLOR="Red"
 declare VERCOLOR="Cyan"
+declare COLOR_START=""
+declare COLOR_END=""
 declare CONFFILE="/etc/imdbdump.conf"
+### End Global
 
-# create tmp directory to work in
-if [ ! -d $HOME/tmp/imdbdump/ ]; then
+### Start tmp check
+if [ ! -d $HOME/tmp/imdbdump/ ]
+then
     echo " We need to create a tmp directory for imdbdump"
     echo "imdbdump uses $HOME/tmp/imdbdump/ by default"
     echo " Creating tmp directory now."
     mkdir -p $HOME/tmp/imdbdump/
 fi
+### End tmp check
 
-#Colors
-if [ -f $HOME/.config/imdbdump.conf ]
-then
-CONFFILE=$HOME/.config/imdbdump.conf
+### Start Config
+if [ -f $HOME/.config/imdbdump.conf ]; then
+    CONFFILE=$HOME/.config/imdbdump.conf
 fi
 if [ ! -f $CONFFILE ]
 then
-echo "$CONFFILE not found, please create it."
-exit 192
+    echo "$CONFFILE not found, please create it."
+    exit 192
 fi
-INEEDCOLOR=0
-. $CONFFILE
+### End Config
+
+### Start Color
+if [ -f $CONFFILE ]
+then
+    declare COLOR_START='\033['
+    declare COLOR_END='\033[0m'
+    . $CONFFILE
+fi
+
 getcolor()
 {
-COMPONENT=$1
-VAR=$2
-case $COMPONENT in
-Black) eval ${VAR}_CODE=30
+  COMPONENT=$1
+  VAR=$2
+  case $COMPONENT in
+  Black) eval ${VAR}_CODE=30
+        eval ${VAR}_MODE=0
+        ;;
+  Red)eval ${VAR}_CODE=31
       eval ${VAR}_MODE=0
       ;;
-Red)eval ${VAR}_CODE=31
-    eval ${VAR}_MODE=0
-    ;;
-Green)eval ${VAR}_CODE=32
-    eval ${VAR}_MODE=0
-   ;;
-Yellow)eval ${VAR}_CODE=33
-    eval ${VAR}_MODE=0
-;;
-Blue)eval ${VAR}_CODE=34
-    eval ${VAR}_MODE=0
-;;
-Purple)eval ${VAR}_CODE=35
-    eval ${VAR}_MODE=0
-;;
-Cyan)eval ${VAR}_CODE=36
-    eval ${VAR}_MODE=0
-;;
-Gray)eval ${VAR}_CODE=37
-    eval ${VAR}_MODE=0
-;;
-DGray)eval ${VAR}_CODE=30
-    eval ${VAR}_MODE=1
-;;
-DRed)eval ${VAR}_CODE=31
-    eval ${VAR}_MODE=1
-;;
-DGreen)eval ${VAR}_CODE=32
-    eval ${VAR}_MODE=1
-;;
-DYellow)eval ${VAR}_CODE=33
-    eval ${VAR}_MODE=1
-;;
-DBlue)eval ${VAR}_CODE=34
-    eval ${VAR}_MODE=1
-;;
-DPurple)eval ${VAR}_CODE=35
-    eval ${VAR}_MODE=1
-;;
-DCyan)eval ${VAR}_CODE=36
-    eval ${VAR}_MODE=1
-;;
-White)eval ${VAR}_CODE=37
-    eval ${VAR}_MODE=1
-;;
-*)eval ${VAR}_CODE=37
-eval ${VAR}_MODE=0
-;;
-esac
+  Green)eval ${VAR}_CODE=32
+      eval ${VAR}_MODE=0
+     ;;
+  Yellow)eval ${VAR}_CODE=33
+      eval ${VAR}_MODE=0
+  ;;
+  Blue)eval ${VAR}_CODE=34
+      eval ${VAR}_MODE=0
+  ;;
+  Purple)eval ${VAR}_CODE=35
+      eval ${VAR}_MODE=0
+  ;;
+  Cyan)eval ${VAR}_CODE=36
+      eval ${VAR}_MODE=0
+  ;;
+  Gray)eval ${VAR}_CODE=37
+      eval ${VAR}_MODE=0
+  ;;
+  DGray)eval ${VAR}_CODE=30
+      eval ${VAR}_MODE=1
+  ;;
+  DRed)eval ${VAR}_CODE=31
+      eval ${VAR}_MODE=1
+  ;;
+  DGreen)eval ${VAR}_CODE=32
+      eval ${VAR}_MODE=1
+  ;;
+  DYellow)eval ${VAR}_CODE=33
+      eval ${VAR}_MODE=1
+  ;;
+  DBlue)eval ${VAR}_CODE=34
+      eval ${VAR}_MODE=1
+  ;;
+  DPurple)eval ${VAR}_CODE=35
+      eval ${VAR}_MODE=1
+  ;;
+  DCyan)eval ${VAR}_CODE=36
+      eval ${VAR}_MODE=1
+  ;;
+  White)eval ${VAR}_CODE=37
+      eval ${VAR}_MODE=1
+  ;;
+  *)eval ${VAR}_CODE=37
+  eval ${VAR}_MODE=0
+  ;;
+  esac
 }
+
 if [ $INEEDCOLOR -eq 1 ]
 then
-getcolor $TITLECOLOR TITLECOLOR
-getcolor $DATACOLOR DATACOLOR
-getcolor $LINKCOLOR LINKCOLOR
-getcolor $FILECOLOR FILECOLOR
-getcolor $VERCOLOR VERCOLOR
+  getcolor $VERCOLOR VERCOLOR
+  getcolor $FILECOLOR FILECOLOR
+  getcolor $TITLECOLOR TITLECOLOR
+  getcolor $DATACOLOR DATACOLOR
+  getcolor $LINKCOLOR LINKCOLOR
 else
-TITLECOLOR="White"
-DATACOLOR="White"
-LINKCOLOR="White"
-FILECOLOR="Red"
-VERCOLOR="Cyan"
-getcolor $TITLECOLOR TITLECOLOR
-getcolor $DATACOLOR DATACOLOR
-getcolor $LINKCOLOR LINKCOLOR
-getcolor $FILECOLOR FILECOLOR
-getcolor $VERCOLOR VERCOLOR
+  VERCOLOR=""
+  FILECOLOR=""
+  TITLECOLOR=""
+  DATACOLOR=""
+  LINKCOLOR=""
 fi
-#End Colors
+### End Colors
 
-#Input Arguments/ Parametrs
-if [ $# -eq 0 ];then
-printf "%s -h for more information\n" "$SCRIPT"
+### Start Input Arguments/ Parametrs
+if [ $# -eq 0 ]
+then
+    printf "%s -h for more information\n" "$SCRIPT"
 exit 192
 fi
 while getopts "$OPTSTRING" SWITCH;do
-case "$SWITCH" in
+    case "$SWITCH" in
 h) cat << EOF
    $SCRIPT [option] [arg]
 
    Options :
    -v : imdbdump version
    -h : display help
-   -t [arg] : Pass the movie title as argument. It is recommended to quote the name as shown in the example below 
+   -t [arg] : Pass the movie title as argument. It is recommended to quote the name as shown in the example below
+   -p : Download movie poster. Use it with -t option.
+   -s : Do not show similar titles.
+   -m : Output in machine-readable format, easy for subsequent parsing. Use it with -t option.
 
    Example :
    $SCRIPT -t "evil dead"
@@ -206,26 +219,28 @@ v) printf "IMDbdump version %s.\nBugs, Feature requests etc : %s\n" "$VERSION" "
     ;;
 esac
 done
-[[ -z $MOVIE ]] && { printf "%s -h for more information\n" "$SCRIPT";exit 192;}
+
+[[ ${MOVIE:-unset} == 'unset' || -z $MOVIE ]] && { printf "Invalid input. Execute %s -h for more information\n" "$SCRIPT";exit 192;}
+
 #functions
 printnofound() {
-printf "There is no $1 command. Please install it\n"
+    printf "There is no $1 command. Please install it\n"
 }
 sancheck() {
 BINARY=$1
 if [ ! -x "$BINARY" ]
 then
-printnofound $BINARY >&2
-exit 192
+    printnofound $BINARY >&2
+    exit 192
 fi
 }
-#End A / P
+### End Input
 
-#Sanity checks
+### Start Sanity checks
 if [ -z "$BASH" ]
 then
-printf "This script is written for bash. Please run this under bash\n" >&2
-exit 192
+    printf "This script is written for bash. Please run this under bash\n" >&2
+    exit 192
 fi
 sancheck $ELINKS
 sancheck $AWK
@@ -236,181 +251,169 @@ sancheck $UNIQ
 sancheck $HEAD
 sancheck $SED
 sancheck $SORT
-#End Sanity Check
+sancheck $TR
+### End Sanity Check
 
-#Replace Special Characters in the Title Name Argument
-MOVIE=`echo $MOVIE | sed -r 's/  */\+/g;s/\&/%26/g;s/\++$//g'`
+### Replace Special Characters in the Title Name Argument
+MOVIE=`echo $MOVIE | $SED -r 's/  */\+/g;s/\&/%26/g;s/\++$//g'`
 
-#Search the Title in Google
+### Search the Title in Google
 $ELINKS -no-numbering --source "http://www.google.com/search?hl=en&q=$MOVIE+imdb" > $TMPFILE 2> /dev/null
 
-#Check if elinks is successful
+### Check if elinks is successful
 if [ $? -ne 0 ]
 then
-printf "Connection to site failed...Please check your internet connection\n"
-exit 192
+    printf "Connection to site failed...Please check your internet connection\n"
+    exit 192
 fi
-#Get IMDB URL for the film
+### Get IMDB URL for the film
 URL=`$EGREP -o "http://www.imdb.com/title/tt[0-9]*/" $TMPFILE | $HEAD -1`
-#Get similar titles
-SIMILARTITLES=`$EGREP -o "<a[^>]+>[^<]*(<em>[^<|^(imdb)]+</em>)*[^<]*<em>[^<]*</em>[^\(|^<]*\([0-9]+\)[^-]+-[^<]*<em>IMDb</em>" $TMPFILE | grep "www.imdb.com" | sort | uniq | sed 's/- <em>IMDb<\/em>//g' | sed 's/<[^>]*>//g'`
-#get the details from movie page
+### Get similar titles
+SIMILARTITLES=`$EGREP -o "<a[^>]+>[^<]*(<b>[^<|^(imdb)]+</b>)*[^<]*<b>[^<]*</b>[^\(|^<]*\([0-9]+\)[^-]+-[^<]*<b>IMDb</b>" $TMPFILE | $GREP "www.imdb.com" | $SORT | $UNIQ | $SED 's/- <b>IMDb<\/b>//g' | $SED 's/<[^>]*>//g'`
+
+### Get the details from movie page
 $ELINKS -source  ${URL} > $TMPFILE;
 if [ $? -ne 0 ]
 then
-printf "Connection to site failed...Please check your internet connection\n"
-exit 192
+    printf "Connection to site failed...Please check your internet connection\n"
+    exit 192
 fi
 
-#extract data
-YEAR=`$CAT $TMPFILE | $SED -n '/<h1.*>/,/<\/h1>/p' | $SED '1d;$d;/^$/d;s/<[^>]*>//g;s/(//g;s/)//g' | $EGREP -o "[0-9][0-9][0-9][0-9]"`
-TITLE=`$CAT $TMPFILE | $SED -n '/<h1.*>/,/<\/h1>/p' | $SED '1d;$d;/^$/d;s/<[^>]*>//g;s/(//g;s/)//g' | $HEAD -1 | $SED "s/\&#x27\;/\'/g" ` #| $ELINKS -dump `
+### Extract Year & Title
+YEAR=`$CAT $TMPFILE | $SED -n '/<h1.*>/,/<\/h1>/p' | $SED -n '/<span class="nobr".*>/,/<\/span>/p' | $SED '/^$/d;s/<[^>]*>//g;s/(//g;s/)//g' | $SED 's/&ndash;/ - /g'| $TR -d ' '`
+TITLE=`$CAT $TMPFILE | $SED -n '/<h1.*>/,/<\/h1>/p' | $SED -n 's/.*itemprop="name">//;s/<.*//p' | $TR -s ' '| $TR '\n' ' '`
 
-POSTERURL=`grep "Poster" $TMPFILE -A1|grep -o http.*\.jpg|cut -f 1 -d "_"`
+### Extract Poster Details
+POSTERURL=`$GREP "Poster" $TMPFILE -A1 | $GREP -o http.*\.jpg | $CUT -f 1 -d "_"`
 POSTERURL=${POSTERURL}jpg
 
 if [ $POSTER -eq 1 ]
 then
-POSTERFILE=`echo $TITLE | $SED "s/ /_/g"`
-  $LYNX -connect_timeout=10 --source $POSTERURL > ${POSTERFILE}.jpg 2> /dev/null
+    POSTERFILE=`echo $TITLE | $SED "s/ /_/g"`
+    $ELINKS -source $POSTERURL > ${POSTERFILE}.jpg 2> /dev/null
 fi
+### End Poster Details
 
-#Get the plot in a html file
-$SED -n '/<h1.*>/,/<\/p>/p' $TMPFILE | $SED -n '/<p>/,/<\/p>/{ s/<[^>]*>//g;p;}' | $SED 's/See full summary.*//g' > $PLOTFILE 
+### Start Get Plot
+$SED -n '/.*<p itemprop="description">/,/<\/p>/p' $TMPFILE | $SED -n 's/.*itemprop="description">//;s/<.*//p' > $PLOTFILE
 PLOT=`$ELINKS --dump $PLOTFILE | $SED 's/^  *//g '`
 RATING=`$SED -n '/<span itemprop="ratingValue">/{ s/<[^>]*>//g;p;}' $TMPFILE  | $EGREP -o "[0-9]+\.[0-9]+/[0-9]+" | tail -1`
-DIRECTOR=`$SED -n '/ *Director[s]*:.*/,/ *Writer[s]*:.*/{p;}' $TMPFILE | $SED '1d;$d' | tr '\n' ' ' | $SED 's/<[^>]*>//g' | $SED 's/^ *//g;s/ *$//g'`
-GENRE=`$SED -n '/genre/p' $TMPFILE | $EGREP -o '<a  *.*href="/genre/[a-zA-Z][a-z]*"[^>]*>[^<]*</a>' | $SED 's/<[^>]*>//g;s/&nbsp\;//g;s/ *Genres *[0-9][0-9]* *min-//g;s/|/,/g' | $SED 's/[gG]enres//g;s/^  *//g' | $UNIQ | $HEAD -1`
-CAST=`$SED -n '/.*Star[s]*:.*/,/<\/div>/{ s/<[^>]*>//g;s/Stars://g;p }' $TMPFILE | $SED -n '/^ *$/d;p' | tr '\n' ' ' | $SED 's/<[^>]*>//g'`
+DIRECTOR=`$SED -n '/ *tt_ov_dr.*/,/<\/div>/{p;}' $TMPFILE | $SED -n 's/.*itemprop="name">//;s/<.*//p'| $UNIQ | $TR -s ' '| $TR '\n' ','| $SED 's/ ,//g;s/^,//;s/,$//'`
+GENRE=`$GREP "ref_=tt_ov_inf" $TMPFILE| $GREP genre | $SED -n 's/.*itemprop="genre">//;s/<.*//p'| $UNIQ | $TR '\n' ','| $SED 's/^,//;s/,$//'`
+CAST=`$SED -n '/ *tt_ov_st.*/,/<\/div>/{p;}' $TMPFILE | $SED -n 's/.*itemprop="name">//;s/<.*//p'| $UNIQ | $TR -s ' '| $TR '\n' ','| $SED 's/ ,//g;s/^,//;s/,$//'`
+### End Get Plot
 
-# Rating star bar
+### Start Rating bar
 SRATE=`$SED -n '/<span itemprop="ratingValue">/{ s/<[^>]*>//g;p;}' $TMPFILE  | $EGREP -o "[0-9]+\.[0-9]+/[0-9]+" | tail -1 | $CUT -f1 -d "/"`
-if [ "$SRATE" == " " ]; then
-  SRATE='0'
+if [ "$SRATE" == " " ]
+then
+    SRATE='0'
 else
-  SRATE=`$SED -n '/<span itemprop="ratingValue">/{ s/<[^>]*>//g;p;}' $TMPFILE  | $EGREP -o "[0-9]+\.[0-9]+/[0-9]+" | tail -1 | $CUT -f1 -d "/" | $CUT -f 1 -d "."`
+    SRATE=`$SED -n '/<span itemprop="ratingValue">/{ s/<[^>]*>//g;p;}' $TMPFILE  | $EGREP -o "[0-9]+\.[0-9]+/[0-9]+" | tail -1 | $CUT -f1 -d "/" | $CUT -f 1 -d "."`
 fi
 
 RBARS=$(expr $SRATE / 1)
 
 case $RBARS in
-#
-        1)
-#
-                BAR='[\033[33m*\033[0m---------]'
-#
-                ;;
-#
-        2)
-#
-                BAR='[\033[33m**\033[0m--------]'
-#
-                ;;
-#
-        3)
-#
-                BAR='[\033[33m***\033[0m-------]'
-#
-                ;;
-#
-        4)
-#
-                BAR='[\033[33m****\033[0m------]'
-#
-                ;;
-#
-        5)
-#
-                BAR='[\033[33m*****\033[0m-----]'
-#
-                ;;
-#
-        6)
-#
-                BAR='[\033[33m******\033[0m----]'
-#
-                ;;
-#
-        7)
-#
-                BAR='[\033[33m*******\033[0m---]'
-#
-                ;;
-#
-        8)
-#
-                BAR='[\033[33m********\033[0m--]'
-#
-                ;;
-#
-        9)
-#
-                BAR='[\033[33m*********\033[0m-]'
-#
-                ;;
-#
-        10)
-#
-                BAR='[\033[33m**********\033[0m]'
-#
-                ;;
-#
-        *)
-#
-                BAR='[----------]'
-#
+    1)
+        BAR='[\033[33m*\033[0m---------]'
+        ;;
+    2)
+        BAR='[\033[33m**\033[0m--------]'
+        ;;
+    3)
+        BAR='[\033[33m***\033[0m-------]'
+        ;;
+    4)
+        BAR='[\033[33m****\033[0m------]'
+        ;;
+    5)
+        BAR='[\033[33m*****\033[0m-----]'
+        ;;
+    6)
+        BAR='[\033[33m******\033[0m----]'
+        ;;
+    7)
+        BAR='[\033[33m*******\033[0m---]'
+        ;;
+    8)
+        BAR='[\033[33m********\033[0m--]'
+        ;;
+    9)
+        BAR='[\033[33m*********\033[0m-]'
+        ;;
+    10)
+        BAR='[\033[33m**********\033[0m]'
+        ;;
+    *)
+        BAR='[----------]'
 esac
-#
+### End Rating Bar
 
+### Start Color Tag
 if [ $INEEDCOLOR -eq 1 ]
 then
-TITLE_COLOR_TAG="${TITLECOLOR_MODE};${TITLECOLOR_CODE}m"
-  DATA_COLOR_TAG="${DATACOLOR_MODE};${DATACOLOR_CODE}m"
-  LINK_COLOR_TAG="${LINKCOLOR_MODE};${LINKCOLOR_CODE}m"
+    VER_COLOR_TAG="${FILECOLOR_MODE};${FILECOLOR_CODE}m"
+    FILE_COLOR_TAG="${FILECOLOR_MODE};${FILECOLOR_CODE}m"
+    TITLE_COLOR_TAG="${TITLECOLOR_MODE};${TITLECOLOR_CODE}m"
+    DATA_COLOR_TAG="${DATACOLOR_MODE};${DATACOLOR_CODE}m"
+    LINK_COLOR_TAG="${LINKCOLOR_MODE};${LINKCOLOR_CODE}m"
 else
-TITLE_COLOR_TAG=""
-  DATA_COLOR_TAG=""
-  LINK_COLOR_TAG=""
+    VER_COLOR_TAG=""
+    FILE_COLOR_TAG=""
+    TITLE_COLOR_TAG=""
+    DATA_COLOR_TAG=""
+    LINK_COLOR_TAG=""
 fi
+### End Color Tag
 
+### Start Parseable
 if [ $PARSEABLE -eq 1 ]
 then
-PLOT=`echo $PLOT | tr -d '\n'`
+    PLOT=`echo $PLOT | $TR -d '\n'`
 fi
+### End Parseable
 
-#print everything
-printf "\n\033[${FILECOLOR_MODE};${FILECOLOR_CODE}m$FILE\033[0m -  \033[${VERCOLOR_MODE};${VERCOLOR_CODE}m$VER\033[0m\n\n"
-printf "\033[${TITLECOLOR_MODE};${TITLECOLOR_CODE}mTitle\033[0m    : \033[${DATACOLOR_MODE};${DATACOLOR_CODE}m$TITLE\033[0m\n"
-printf "\033[${TITLECOLOR_MODE};${TITLECOLOR_CODE}mIMDdURL\033[0m  : \033[${LINKCOLOR_MODE};${LINKCOLOR_CODE}m${URL}\033[0m\n"
-printf "\033[${TITLECOLOR_MODE};${TITLECOLOR_CODE}mYear\033[0m     : \033[${DATACOLOR_MODE};${DATACOLOR_CODE}m$YEAR\033[0m\n"
-printf "\033[${TITLECOLOR_MODE};${TITLECOLOR_CODE}mRating\033[0m   : \033[${DATACOLOR_MODE};${DATACOLOR_CODE}m$RATING\033[0m $BAR\n"
-printf "\033[${TITLECOLOR_MODE};${TITLECOLOR_CODE}mDirector\033[0m : \033[${DATACOLOR_MODE};${DATACOLOR_CODE}m$DIRECTOR\033[0m\n"
-printf "\033[${TITLECOLOR_MODE};${TITLECOLOR_CODE}mGenres\033[0m   : \033[${DATACOLOR_MODE};${DATACOLOR_CODE}m$GENRE\033[0m\n"
-printf "\033[${TITLECOLOR_MODE};${TITLECOLOR_CODE}mCast\033[0m     : \033[${DATACOLOR_MODE};${DATACOLOR_CODE}m$CAST\033[0m\n"
-printf "\033[${TITLECOLOR_MODE};${TITLECOLOR_CODE}mPlot\033[0m     :\033[${DATACOLOR_MODE};${DATACOLOR_CODE}m$PLOT\n"
+### Start Printing everything
+printf "\n${COLOR_START}${FILE_COLOR_TAG}$FILE${COLOR_END}   : ${COLOR_START}${VER_COLOR_TAG}$VER${COLOR_END}\n"
+printf "${COLOR_START}${TITLE_COLOR_TAG}Title${COLOR_END}      : ${COLOR_START}${DATA_COLOR_TAG}$TITLE${COLOR_END}\n"
+printf "${COLOR_START}${TITLE_COLOR_TAG}Year${COLOR_END}       : ${COLOR_START}${DATA_COLOR_TAG}$YEAR${COLOR_END}\n"
+printf "${COLOR_START}${TITLE_COLOR_TAG}Rating${COLOR_END}     : ${COLOR_START}${DATA_COLOR_TAG}$RATING${COLOR_END} $BAR\n"
+printf "${COLOR_START}${TITLE_COLOR_TAG}Director${COLOR_END}   : ${COLOR_START}${DATA_COLOR_TAG}$DIRECTOR${COLOR_END}\n"
+printf "${COLOR_START}${TITLE_COLOR_TAG}Genres${COLOR_END}     : ${COLOR_START}${DATA_COLOR_TAG}$GENRE${COLOR_END}\n"
+printf "${COLOR_START}${TITLE_COLOR_TAG}Cast${COLOR_END}       : ${COLOR_START}${DATA_COLOR_TAG}$CAST${COLOR_END}\n"
+#printf "${COLOR_START}${TITLE_COLOR_TAG}Plot${COLOR_END} : ${COLOR_START}${DATA_COLOR_TAG}%s${COLOR_END}\n" "$PLOT"
+printf "${COLOR_START}${TITLE_COLOR_TAG}Plot${COLOR_END}       : ${COLOR_START}${DATA_COLOR_TAG}%s${COLOR_END}\n" "$PLOT"
+printf "\n${COLOR_START}${TITLE_COLOR_TAG}IMDbURL${COLOR_END}    : ${COLOR_START}${LINK_COLOR_TAG}${URL}${COLOR_END}\n"
+printf "${COLOR_START}${TITLE_COLOR_TAG}Poster URL${COLOR_END} : ${COLOR_START}${LINK_COLOR_TAG}${POSTERURL}${COLOR_END}\n"
+### End Print
 
+### Start Similar & Parseable
 if [ $SIMILAR -eq 1 ]
 then
-if [ $PARSEABLE -eq 0 ]
-  then
-printf "${COLOR_START}${TITLE_COLOR_TAG}\n==============Other similar Titles=============${COLOR_END}\n\n"
-    if [ -z "$SIMILARTITLES" ]
+    if [ $PARSEABLE -eq 0 ]
     then
-SIMILARTITLES="Nothing interesting here"
-    fi
-printf "${COLOR_START}${DATA_COLOR_TAG}%s${COLOR_END}\n" "$SIMILARTITLES"
-    printf "\n${COLOR_START}${TITLE_COLOR_TAG}Use above key words to know more about them${COLOR_END}\n"
-  else
-if [ ! -z "$SIMILARTITLES" ]
-    then
-printf "%s" "$SIMILARTITLES" > $TMPFILE.sim
-      cat $TMPFILE|xargs -i echo "Similarities : "{}
-      rm -f $TMPFILE > /dev/null
+        printf "${COLOR_START}${TITLE_COLOR_TAG}\n==============Other similar Titles=============${COLOR_END}\n\n"
+        if [ -z "$SIMILARTITLES" ]
+        then
+            SIMILARTITLES="Nothing interesting here"
+        fi
+        printf "${COLOR_START}${DATA_COLOR_TAG}%s${COLOR_END}\n" "$SIMILARTITLES"
+        printf "\n${COLOR_START}${TITLE_COLOR_TAG}Use above key words to know more about them${COLOR_END}\n"
+    else
+        if [ ! -z "$SIMILARTITLES" ]
+        then
+            printf "%s" "$SIMILARTITLES" > $TMPFILE.sim
+            cat $TMPFILE|xargs -i echo "Similarities : "{}
+            rm -f $TMPFILE.sim > /dev/null
+        fi
     fi
 fi
-fi
+### End Similar & Parseable
 
-#Done. Now do cleanup
+### Start Clean Up
 rm $TMPFILE > /dev/null
 rm $PLOTFILE > /dev/null
+### End Clean Up
+
 exit 0
